services:
  - type: web
    runtime: node
    name: inventory-track-api
    buildCommand: "npm install && npm run build:frontend"
    startCommand: "npm start"
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 2h
