services:
  - type: web_service
    name: inventory-track-api
    env: node
    branch: main
    buildCommand: "npm run build:frontend"
    startCommand: "npm start"
    env:
      NODE_ENV: production
